### ISSUE TITLE
folder's name in view directory from todolist

### ISSUE THREAD

**Issue by kvhsn** [kleliboux/code-samples#1]
I forked your repo and I discovered a litte mistake with the View.php.
Indeed, you have written that : 

```php
public function display() {
   $viewFile = ROOT . "/app/view/" . $this->_route["controller"] . "/" . $this->_route["action"] . ".html";
```

However, your folder's name are in lowercase so you need to put **$this->_route["controller"]** in lowercase or just rename *index* to *Index*

**Comment by kleliboux** [comment]
You're right I guess. Merci beaucoup ;)
